### ISSUE TITLE
new install or update

### ISSUE THREAD

**Issue by gedw99** [Pyozer/introduction_screen#1]
It would be cool if users get told how the app works ( new install) Or new features ( upgrade )

I think there is a flutter plugin to do this..

**Comment by Pyozer** [comment]
Sorry I don't understand what you want to say :/
This is not an app, it's a package. And this package can be integrated to an existing app.

**Comment by gedw99** [comment]
I will add it myself.

Basically you want to detect if it's a new I stall OR an upgrade of the app
and then show different message as a result.

No worries

**Comment by gedw99** [comment]
Here it is

https://github.com/jogboms/flutter_offline

**Comment by Pyozer** [comment]
Oh ok I understand ;) I think it's not the role of this package to handle if it's new install or an update.
You need to pass a different list of PageViewModel, depend if it's a new install or update.

To check this, you can store (SharedPreferences) a boolean (isFirstBoot) and when onDone() press change it to "false". Also store a String (lastAppVersion) with the actual version of the app (when the onDone() pressed, change it with actual version).
If "isFirstBoot" is null or true, it's new install. And if not first boot but the actual version is different with store version (lastAppVersion) so it's an update.
