### ISSUE TITLE
Positioning of dots, next and skip buttons.

### ISSUE THREAD

**Issue by neha-ajith** [Pyozer/introduction_screen#103]
I wanted to position the dots vertically above the next button as in the image. As of now, after a lot of research, I haven't found a way to do this.

![Onboarding1](https://user-images.githubusercontent.com/62176326/151802851-52971d28-39d1-4699-b1cd-7ad7fda77c47.png)

**Comment by Pyozer** [comment]
Hi, I've not tested but you can try to use `globalFooter` to add your next button and disable other buttons with `showNextButton` param.
To have a working custom next button, you have to create a key to access internal next function (see example app or issue for more details).

**Comment by gamcho3** [comment]
I also want to solution. did you done it?

**Comment by Pyozer** [comment]
Hi @gamcho3, did you try my previous solution ?

**Comment by gamcho3** [comment]
I can't find your solution. I'm sorry. I have another question.  can I require page index? I want to control show and next button depends on page.

**Comment by gamcho3** [comment]
> Hi @gamcho3, did you try my previous solution ?
I can't find your solution. I'm sorry.

**Comment by connelevalsam** [comment]
I'm stuck with this. No example on how to do something like this is even available. At least he would have looked at all the possibilities. You don't expect us to just use 1 design

**Comment by Pyozer** [comment]
Use another lib if this not matching with your requirements.
I will not made introduction_screen more complex than actual just to match with 100% of Flutter devs.

**Comment by mohadel92** [comment]
you can use empty container with global footer to move dots @neha-ajith
