### ISSUE TITLE
How to create dynamic Introduction Screen?

### ISSUE THREAD

**Issue by JayswalViraj** [Pyozer/introduction_screen#106]
Like I am pass data in api ( admin panel ) like 3 pages introduction screen. after introduction screen draw 3 pages. after I am pass 4 screen in api ( admin  panel ), introduction screen draw 4 pages. is this possibel?

Thank you for giving me your important time.

**Comment by Pyozer** [comment]
Hi, sorry I'm not quite understand what you want.
From what I understand you want to change number of pages dynamically (or more generally change pages) ?

I think you can just update `pages` parameter, not tested.

**Comment by ghenry** [comment]
Hi @JayswalViraj 

I'm going to close this as we presume you're all OK. This really isn't an issue for this project either, more of a Flutter app design decision for you. Did you try on SO or the Flutter mailing list?

Thanks,
Gavin.
