### ISSUE TITLE
How to set the contents(like title,body,image) in center on page? 

### ISSUE THREAD

**Issue by debugerer** [Pyozer/introduction_screen#11]
The default is from top to bottom, Could I change it in center?

**Comment by rahuljidgedev** [comment]
Can you guys add a code snippet about how to align a simple Text("Hello world") widget to center in PageViewModel()?

**Comment by Pyozer** [comment]
Hi, very sorry for the late reply.. more than 1 year :/
In the next update (very soon available) you will be able to provide `bodyAlignment` and `imageAlignment` in PageDecoration to change alignment of titre/subtitle and/or image.
I close this issue, if you have more question or bug, re-open it.
Sorry gain.

**Comment by nicks258** [comment]
Not able to find `imageAlignment `in PageDecoration in 2.0.0 @Pyozer

**Comment by Pyozer** [comment]
@nicks258 It's will be available in next update (2.1.0), maybe available today or tomorrow.
If you want to test now on your app, you can import package using git.
