### ISSUE TITLE
Dependency collection 1.16.0 conflict on introduction screen vs latest Flutter 2.10.4 (stable)

### ISSUE THREAD

**Issue by cybex-dev** [Pyozer/introduction_screen#113]
**_This isn't an issue, more just a suggestions and an fyi._**

Using latest Flutter (stable), there is an upgrade/update conflict with [flutter_test](https://github.com/flutter/flutter/tree/master/packages/flutter_test) with [collections](https://pub.dev/packages/collection) 1.16.0 dependency. 

**Cause**
As of [Flutter 2.10.4](https://github.com/flutter/flutter/releases/tag/2.10.4) (published 2 days ago), a [fix for this issue](https://github.com/flutter/flutter/commit/1880066dd3a092703e8985e188b8774e40a181b8#diff-7aeed2684fbb97f9ecaeecc02b1a84ae2a347f2d1a8a4c85119f0d0021598e2cR27) has been added (16 days ago) but has not yet been added to the latest Flutter update.

**Temporary fix:** 
use `introduction_screen: ^3.0.0`

**flutter doctor -v**
```

[✓] Flutter (Channel stable, 2.10.4, on Arch Linux 5.16.13-arch1-1, locale en_US.UTF-8)
    • Flutter version 2.10.4 at /home/cybex/.flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

```

**pubspec.yaml**

```
environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.0.1
    ...

dev_dependencies:
  flutter_test:
    sdk: flutter
```

**Flutter error**
```
Running "flutter pub get" in app...           
Because every version of flutter_test from sdk depends on collection 1.15.0 and introduction_screen >=3.0.1 depends on collection ^1.16.0, flutter_test from sdk is incompatible with introduction_screen >=3.0.1.
So, because app depends on both introduction_screen ^3.0.1 and flutter_test from sdk, version solving failed.
Process finished with exit code 1
```

**Comment by techouse** [comment]
Downgrading `collections` to `1.15.0` should resolve it unless there are any specific needs for `1.16.0`

**Comment by Pyozer** [comment]
Hi, sorry for that, I will downgrade collections to `1.15.0`
