### ISSUE TITLE
Specify different colour for left inactive to right inactive

### ISSUE THREAD

**Issue by BenBtg** [Pyozer/introduction_screen#114]
I need a way to be able to specify that active page has a blue dot, completed pages have green dots and incomplete pages have grey dots. This does not seem to be possible as you can only set a colour for all inactive dots.

**Comment by ghenry** [comment]
Hi @BenBtg BenBtg,

Is this still a requirement or have you moved on? Or, fingers crossed, you could contribute an option for the project?

I'll close this issue now. Feel free to re-open by tagging it in your PR :-)

Many thanks,
Gavin.

**Comment by BenBtg** [comment]
Yes I did move on with a quick workaround. But will see if I can find time to roll a better implementation into a PR.
