### ISSUE TITLE
Disable swipe back gesture

### ISSUE THREAD

**Issue by FrazeColder** [Pyozer/introduction_screen#115]
First of all thank you for that amazing package!

I have deactivated the the back button. However, it is still possible for the user to go back with the back/left swipe gesture. Is there any possiblity to prevent that. If so, how can I achive that?

Kind regards

**Comment by FrazeColder** [comment]
I just found out that it works via `freeze: true`. However, one question regarding this:

If the onboarding screen text plus image requires to be scrolled (e.g. text plus image is to long), will this be possible than?
Or will `freeze: true` deactivate the complete scroll feature?

**Comment by ghenry** [comment]
Hi @FrazeColder 

I'm presuming you found a solution. If not, please re-open.

Many thanks,
Gavin.
