### ISSUE TITLE
Just show the Introduction Screen once, after the very first start of the app

### ISSUE THREAD

**Issue by Azzeccagarbugli** [Pyozer/introduction_screen#12]
Hi @Pyozer,

First of all thanks for this **wonderful** plugin that you made for us! 

I was wondering if would be possible to show the plugin just once after the very first start of the app. 

Would be really cool that somehow the Introduction Screen would be able to understand, with a state manager or a cache system, that the user already saw it and not show the plugin again.

Thanks for everything, cheers!

**Comment by VictorUvarov** [comment]
You would be better off caching if the screen has been shown yourself. If you have a sign/sign up functionality only show the intro screen when the user signs up.

**Comment by Azzeccagarbugli** [comment]
Thanks a lot @VictorUvarov, I actually did _more or less_ what you suggested and everything is working fine!
