### ISSUE TITLE
Conditions for done button

### ISSUE THREAD

**Issue by Sesa1988** [Pyozer/introduction_screen#122]
Is it possible to disable the next and done button temporary until my viewmodel meet that condition criteria?

The point here would be that this specific viewmodel would be in charge of the state.

It could fetch some data from an API and if only it is finished you can click next.

**Comment by ghenry** [comment]
Hi @Sesa1988  

I'm presuming you've figured this out or found a different solution. If so, please share :-)

I'm going to close this issue in the meantime.

Many thanks,
Gavin.
