### ISSUE TITLE
Add option to automatically move through the intro pages?

### ISSUE THREAD

**Issue by les-larsj** [Pyozer/introduction_screen#124]
This is a great package but would be even better if you could add the option to auto play through the intro pages until the last one where you then stop and wait for the user to press Done (I have seen a few iOS apps doing this now).
It would also be good to be able to specify the time spent on each intro page before moving on to the next one.
Do you think this would be possible?

Les

**Comment by Pyozer** [comment]
Hi, sorry I've not planned to do it.
Not much time to maintain this project and handle current issues :/ 

You can already wrap the IntroductionScreen with an automatic scroll.
I've never do it, but I think it's possible by using some exposed functions (https://github.com/Pyozer/introduction_screen/issues/89).

If you are motivated, you can do a PR to add an automatic scroll build-in.

**Comment by les-larsj** [comment]
Many thanks, will try to do it using the exposed functions.

**Comment by ghenry** [comment]
Hi @irxyad

I'm presuming you found a solution and am closing this issue. If you could share anything that would benefits other project users, that would be awesome!

Many thanks,
Gavin.
