### ISSUE TITLE
Can I navigate to the next page through a button click in the middle of the screen?

### ISSUE THREAD

**Issue by Sadoun-Jr** [Pyozer/introduction_screen#128]
I'd like to trigger the call to navigate to the next page in the introductory screen using another button than the one in the bottom navigation bar. Is this possible?

**Comment by Pyozer** [comment]
https://github.com/Pyozer/introduction_screen/issues/89

**Comment by Sadoun-Jr** [comment]
Thank you very much! works like a charm :)
