### ISSUE TITLE
How to make Next and Button Full Width?

### ISSUE THREAD

**Issue by andriansandi** [Pyozer/introduction_screen#139]
I have an issue when make button for Next and Button full width, I was using the SizedBox but it always dissapear. Can you help me?

**Comment by diegoalex** [comment]
Same problem around here.
I've been trying to use the  overrideDone, but always  crash when I tried to make the button full width.  (I've used Expanded, infinity width, sized box, etc..)


The idea is build something like that:
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/3237570/193062699-a9c4c3a8-cf56-42a1-bcf4-3584828fc5c5.png">

**Comment by ghenry** [comment]
Hi all,

I'm presuming you've found a solution to this issue? If so, please share. In the meantime I'm closing for now.

Thanks,
Gavin.
