### ISSUE TITLE
How can i use full screen background image for onboarding?

### ISSUE THREAD

**Issue by Swapnil7711** [Pyozer/introduction_screen#14]
I want to set images as background and on top of that I want to display buttons.

**Comment by Pyozer** [comment]
Hi @Swapnil7711, sorry for more than 1 year late reply :/

Hope you have found a solution.
I merged a PR #29 to support fullscreen image as background, release will be very soon published on Pub.
You can also define an image as background of all pages #17 #9.

I close this issue, if you have any other question for this issue, re-open it ;)
