### ISSUE TITLE
Change page programatically

### ISSUE THREAD

**Issue by SoYoureAWaffleMan** [Pyozer/introduction_screen#142]
Great package, saved me a load of time, thanks. 

Feature request: I would like to animate to the next screen (same as tapping next) in response to a user interaction with the page content. The use case is: "requesting app permissions during app intro" which I assume is fairly common. See example screenshot:
![Screenshot from 2022-10-13 14-05-39](https://user-images.githubusercontent.com/6367213/195604566-625b202c-49f7-4fbf-a825-d98333007cb1.png)

Once the user taps "Allow notifications" & then taps OK in system overlay, I want to animate to the next intro page.

The `IntroductionScreen` class offers `initialPage` param but updating that value does not rebuild the `IntroductionScreen` widget. I can force rebuild by passing a `ValueKey` to `key` param but that does not result in animation from the current page to the next.

I think the best approach is to replace `initialPage` with `currentPage`, allowing consuming code to control it; or to add a `forcePage` param which overrides the derived value.

**Comment by Pyozer** [comment]
Hi,

Thank you for your feedback !

You can use a key to control pages.
More info here https://github.com/Pyozer/introduction_screen/issues/62 or https://github.com/Pyozer/introduction_screen/issues/89

**Comment by SoYoureAWaffleMan** [comment]
Ah I see that in the README now 🤦 thanks for the guidance.

I'd be happy to PR a README section about controlling pages if that would be useful.

**Comment by M-S-KHAN** [comment]
Yes @SoYoureAWaffleMan! I was facing the same issue and found a solution in #62 
I believe this section should be added in the README.

**Comment by ghenry** [comment]
Hi all,

@SoYoureAWaffleMan @M-S-KHAN 

Any chance of that Readme pull request? It would be much appreciated!

Thanks,
Gavin.
