### ISSUE TITLE
How to call onDone when last page.

### ISSUE THREAD

**Issue by Ednokia777** [Pyozer/introduction_screen#144]
I have a button, that calls a fun 'to next indruductionPage'. I would like to open my HomePage if i click on 'Next' in the last introduction screens. How can i do it? How to check the last page?

**Comment by ghenry** [comment]
Hi @Ednokia777 

I find with any project on GitHub that it's always best to search in closed issues, source code or the readme for examples of callbacks you're trying to use. See this and search for `onDone`. You should find an idea :-)

https://github.com/Pyozer/introduction_screen/issues/146

I'm going to close this now. Come back any time!

Thanks,
Gavin.
