### ISSUE TITLE
Prep new release - 3.1.0?

### ISSUE THREAD

**Issue by ghenry** [Pyozer/introduction_screen#149]
Hi @Pyozer 

Should we prep a new release, say 3.1.0 listing any potential breaking changes due to all the merged PRs?

They all add new features however, so I think we'll be good. I'll run the example again to check though. I'm just waiting for #143 and #138 to get back to us, but they aren't blockers.

Thanks,
Gavin.

**Comment by ghenry** [comment]
Example app running fine on Android 13 sim and physical device. Will test on iOS sim and physical tomorrow.

**Comment by Pyozer** [comment]
Hi @ghenry,

Thank you very much, it's really great everything you have done for the project !
I will made the release tomorrow ;)

**Comment by ghenry** [comment]
My pleasure! I hope it's taken a bit of pressure of you now and you can relax a bit.

**Comment by ghenry** [comment]
Runs fine on latest Xcode and macOS on a MacBook Air M2 (apple silicon) - https://github.com/Pyozer/introduction_screen/commit/9dde9e2f97d65842995381e3888f192e9a3ea8a2

Can't test a real device with the example as it tries to register the app id to my Apple dev account, so will report any issues when I test in my own project.

Thanks!

**Comment by ghenry** [comment]
We have tests now too :-)

**Comment by ghenry** [comment]
Morning,

Would you like to show me how to do all the pub.dev tasks, or I can Google and then I just need perms. 

Then I can automate a release when we make a new tag.

Thanks.

**Comment by Pyozer** [comment]
Hello, sorry I finally didn't find the time to do the release, but I don't forget. 
I will try today, I should be able by late afternoon. 
Yes why not give you the rights to publish, I'll see that. 

Thanks again for all the hard work!

**Comment by ghenry** [comment]
No worries. Look forward to continuing to help out!

**Comment by Pyozer** [comment]
New release 3.1.0 published 🎉🎉
Thanks again !

I looked into adding you as a publisher, can you give me your email address? I've accepted you on LinkedIn, you can send it to me by message ;)

**Comment by ghenry** [comment]
Congratulations!

**Comment by ghenry** [comment]
I've done a release and created a v3.1.0 tag https://github.com/Pyozer/introduction_screen/releases/tag/v3.1.0

Closing now. Nice team work!
