### ISSUE TITLE
Bug: Not compiling at Flutter Master after latest update

### ISSUE THREAD

**Issue by brunodmn** [Pyozer/introduction_screen#151]
**Describe the bug**
It just stopped compiling after latest Flutter Master upgrade

**To Reproduce**
1. change to master channel with `flutter channel master` and `flutter upgrade`
2. run your application

**Additional context**
<details>
<summary>Logs</summary>
../../.pub-cache/hosted/pub.dev/introduction_screen-3.1.0/lib/src/introduction_screen.dart:505:35: Error: The method 'elementAtOrNull' is defined in multiple extensions for 'List<ScrollController?>' and neither is more specific.
 - 'List' is from 'dart:core'.
 - 'ScrollController' is from 'package:flutter/src/widgets/scroll_controller.dart' ('../flutter/packages/flutter/lib/src/widgets/scroll_controller.dart').
Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
                                ?.elementAtOrNull(index),
                                  ^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/collection-1.17.0/lib/src/list_extensions.dart:271:6: Context: This is one of the extension members.
  E? elementAtOrNull(int index) => (index < length) ? this[index] : null;
     ^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/introduction_screen-3.1.0/lib/src/helper.dart:6:6: Context: This is one of the extension members.
  T? elementAtOrNull(int index) {
     ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.
</details>

**Comment by ghenry** [comment]
Hi @brunodmn

Thanks for this. We only test on flutter stable at the moment.

Gavin.

**Comment by ghenry** [comment]
So when master becomes stable, we'll need to update our helper.

Will leave open and take look when I can.

Thanks for the report. 

What features are you using from master anyway?

**Comment by brunodmn** [comment]
Hi @ghenry , 

Thank you for quick reply and congrats for the nice job and to share it with us. 

 I am working on a Material You project and master is quite ahead. I tried to change to stable bug got a bit uglier in design. 
 My options are redesign or remove your package, if this bug is to hard to fix. 
 Would be a shame to remove your package as you did such a nice job, but would consume me much less time.
 I would totally understand if you consider this not a bug (as it's not  showing on stable channel) and close this thread.

Thanks

**Comment by ghenry** [comment]
No worries. I'm just helping maintain, not the creator :)

I'll have a look, but a fix must be backward compatible, so it depends...

Will let you know.

Thanks.

**Comment by kaboc** [comment]
I'm experiencing the issue on the stable version of Flutter. It occurs if the app project is using package:collection 1.17.0.

**Comment by ghenry** [comment]
I'll ccommit a change after testing again on stable, but Flutter master is working now. Updated our code to pick the extension:

https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=ambiguous_extension_member_access#ambiguous_extension_member_access

Gavin.

**Comment by ghenry** [comment]
That should be you now @brunodmn 

I'll get a release prepared, but you might need to run from git for now.

**Comment by ghenry** [comment]
Done! https://pub.dev/packages/introduction_screen

**Comment by brunodmn** [comment]
Worked! 
Thanks a lot
