### ISSUE TITLE
Bug: The position of the dots change from the first page to the others

### ISSUE THREAD

**Issue by Macacoazul01** [Pyozer/introduction_screen#155]
**Describe the bug**
On the first page of the introduction screen, the dots are lower than on the next ones. so there is a perceptible jump between the screens.

**To Reproduce**
Just create an introduction screen with more than 2 pages and click next.
It's important to have `showBackButton: true,` as it won't happen if the button isn't there

I'm currently using these settings:

```
showBackButton: true,
back: const Icon(
Icons.arrow_back,
color: lumiGreenGray,
),
freeze: true,
dotsFlex: 2,
showNextButton: false,
showDoneButton: false,
curve: Curves.fastLinearToSlowEaseIn,
controlsMargin: const EdgeInsets.all(16),
controlsPadding:EdgeInsets.symmetric(vertical: altDez, horizontal: largCinco),
dotsDecorator: const DotsDecorator(
size: Size(15, 15),
color: Color(0xFFBDBDBD),
activeColor: lumiGreenGray,
activeSize: Size(22, 15),
activeShape: RoundedRectangleBorder(
borderRadius: BorderRadius.all(Radius.circular(25)),
),
),
```

**Screenshots**
![image](https://user-images.githubusercontent.com/57464965/210663061-f1e59eab-86e3-4dcc-9385-45f4b0871eb5.png)

![image](https://user-images.githubusercontent.com/57464965/210662979-8dbd052c-23f9-4122-8847-24ffdec7e020.png)

**Comment by ghenry** [comment]
Hi @Macacoazul01 

Can you reproduce this in our [example app](https://github.com/Pyozer/introduction_screen/tree/master/example) for me in a repo I can look at?

Thanks.

**Comment by Macacoazul01** [comment]
[dots jump.zip](https://github.com/Pyozer/introduction_screen/files/10355905/dots.jump.zip)
@ghenry

**Comment by ghenry** [comment]
Thanks. Going to close this and stick with #156

**Comment by Macacoazul01** [comment]
The 'jump'  is because of this lines in `introduction_screen.dart` file (450-496):

```
final isLastPage = (_currentPage.round() == getPagesLength() - 1);

    Widget? leftBtn;
    if (widget.showSkipButton) {
      leftBtn = Visibility(
        visible: !isLastPage && !_isSkipPressed,
        maintainState: true,
        // Needs to be true to maintain animation
        maintainAnimation: true,
        // Needs to be true to maintain size
        maintainSize: true,
        child: widget.overrideSkip ??
            IntroButton(
              child: widget.skip!,
              style: widget.baseBtnStyle?.merge(widget.skipStyle) ?? widget.skipStyle,
              semanticLabel: widget.skipSemantic,
              onPressed: _onSkip,
            ),
      );
    } else if (widget.showBackButton && _currentPage.round() > 0) {
      leftBtn = widget.overrideBack ??
          IntroButton(
            child: widget.back!,
            style: widget.baseBtnStyle?.merge(widget.backStyle) ?? widget.backStyle,
            semanticLabel: widget.backSemantic,
            onPressed: !_isScrolling ? previous : null,
          );
    }

    Widget? rightBtn;
    if (isLastPage && widget.showDoneButton) {
      rightBtn = widget.overrideDone ??
          IntroButton(
            child: widget.done!,
            style: widget.baseBtnStyle?.merge(widget.doneStyle) ?? widget.doneStyle,
            semanticLabel: widget.doneSemantic,
            onPressed: !_isScrolling ? widget.onDone : null,
          );
    } else if (!isLastPage && widget.showNextButton) {
      rightBtn = widget.overrideNext ??
          IntroButton(
            child: widget.next!,
            style: widget.baseBtnStyle?.merge(widget.nextStyle) ?? widget.nextStyle,
            semanticLabel: widget.nextSemantic,
            onPressed: !_isScrolling ? next : null,
          );
    }
```

It happens if you set `showBackButton = true` with `showNextButton = false` (maybe there are another combinations of buttons that show this same effect, only tested this one)

because the row containing the dots and buttons passes from a state with only the dots, from one with dots and a button.

There are some ways to solve the jump on the y axis 1- setting the `crossAxisAlignment: CrossAxisAlignment.end` on the row ->it causes this type of visual:
![image](https://user-images.githubusercontent.com/57464965/211031053-8cacb7e2-fa07-42f2-a837-c0acb101f6ad.png)
2- making the row already count the height of the buttons on these sizedboxes on lines 556 and 578:
```
Expanded(
  flex: widget.skipOrBackFlex,
  child: leftBtn ?? const SizedBox(),
),
```

```
Expanded(
  flex: widget.nextFlex,
  child: rightBtn ?? const SizedBox(),
),
```

**Comment by Macacoazul01** [comment]
The first one is the easier and 'uglier', the second one will be more expensive in time (and probably flutter resources)

Do you have any idea on how to fix this?

**Comment by ghenry** [comment]
I have re-opened this. I only really maintain this project, but maybe @Pyozer will have a look at some point. I'll try next week and do a release too for #157

**Comment by Macacoazul01** [comment]
@ghenry when are you planning to release the next version?

**Comment by ghenry** [comment]
Morning! Can do later today. Will let you know. Thanks.

**Comment by ghenry** [comment]
Done - https://pub.dev/packages/introduction_screen

**Comment by Macacoazul01** [comment]
Gonna test a little more 3.1.3 before trying to help with this dots problem.

Maybe there are some changes that I can do to the new footer.

I was thinking about replacing the Expanded with a Flexible for it (with flexfit.tight).
What do you think?

**Comment by ghenry** [comment]
Sounds good. Try it out. Benefits?

**Comment by Macacoazul01** [comment]
@ghenry ill try to solve this maybe in the next few days.

if i can't i will try to solve it after returning from vacation
