### ISSUE TITLE
Question: the best way to maintain the footer on the same position between screens

### ISSUE THREAD

**Issue by Macacoazul01** [Pyozer/introduction_screen#156]
Depending on what i have on the body widget, my footer position changes on the screen.

Is there any way to make the position constant on every screen?

Maybe if the footer is a separated parameter from the body it could be easier.

I've already tried global footer but it is positioned bellow the dot progress indicator

![image](https://user-images.githubusercontent.com/57464965/210664301-e5f28074-2aa9-4a2e-b33f-55fa4b0591a4.png)
![image](https://user-images.githubusercontent.com/57464965/210664308-be41a658-0747-4432-bdd3-dec7e0b49a2a.png)

with global footer:
![image](https://user-images.githubusercontent.com/57464965/210664544-277cd0db-1d42-41af-a0d3-605fbc3d467a.png)

**Comment by ghenry** [comment]
Hi @Macacoazul01 

Can you reproduce this in our [example app](https://github.com/Pyozer/introduction_screen/tree/master/example) for me in a repo I can look at?

Thanks.

**Comment by Macacoazul01** [comment]
Used your sample app reducing the number of the pages and changing the `IntroductionScreen` parameters:
[error.zip](https://github.com/Pyozer/introduction_screen/files/10355972/error.zip)

with a footer inside page its easy to see that it's position changes between screens because of the different contents:
![image](https://user-images.githubusercontent.com/57464965/210889580-89b688d2-df9a-4007-92e9-571ba5782b57.png)

Using `reverse = true` the problem of the footer being part of the body becomes even more apparent, as it comes before of the image and not on the end of the screen:
![image](https://user-images.githubusercontent.com/57464965/210889469-252606ca-1c67-4542-8b9d-f9b76c4e5c63.png)

**Comment by Macacoazul01** [comment]
That's why i think that the `footer` parameter inside `PageViewModel` should be constructed outside the `body`/`bodyWidget`

**Comment by Macacoazul01** [comment]
it'll be easier for the devs to control the behavior of the package, and if they want the older one, it's just simple as using a column as `bodywidget` and putting the "footer button" inside it

**Comment by ghenry** [comment]
Would you like to try and change this yourself and do a Pull Request?

**Comment by Macacoazul01** [comment]
Can you point on the code where each one of the things is generated?
I'm running low on free time these days so I don't know if i can solve this right now (but gonna try)

**Comment by ghenry** [comment]
Looks good. Thanks for taking the time to do this. You happy it solves your problem?

**Comment by Macacoazul01** [comment]
The 'jump' of #155 is because of this lines in `introduction_screen.dart` file (450-496):

```
final isLastPage = (_currentPage.round() == getPagesLength() - 1);

    Widget? leftBtn;
    if (widget.showSkipButton) {
      leftBtn = Visibility(
        visible: !isLastPage && !_isSkipPressed,
        maintainState: true,
        // Needs to be true to maintain animation
        maintainAnimation: true,
        // Needs to be true to maintain size
        maintainSize: true,
        child: widget.overrideSkip ??
            IntroButton(
              child: widget.skip!,
              style: widget.baseBtnStyle?.merge(widget.skipStyle) ?? widget.skipStyle,
              semanticLabel: widget.skipSemantic,
              onPressed: _onSkip,
            ),
      );
    } else if (widget.showBackButton && _currentPage.round() > 0) {
      leftBtn = widget.overrideBack ??
          IntroButton(
            child: widget.back!,
            style: widget.baseBtnStyle?.merge(widget.backStyle) ?? widget.backStyle,
            semanticLabel: widget.backSemantic,
            onPressed: !_isScrolling ? previous : null,
          );
    }

    Widget? rightBtn;
    if (isLastPage && widget.showDoneButton) {
      rightBtn = widget.overrideDone ??
          IntroButton(
            child: widget.done!,
            style: widget.baseBtnStyle?.merge(widget.doneStyle) ?? widget.doneStyle,
            semanticLabel: widget.doneSemantic,
            onPressed: !_isScrolling ? widget.onDone : null,
          );
    } else if (!isLastPage && widget.showNextButton) {
      rightBtn = widget.overrideNext ??
          IntroButton(
            child: widget.next!,
            style: widget.baseBtnStyle?.merge(widget.nextStyle) ?? widget.nextStyle,
            semanticLabel: widget.nextSemantic,
            onPressed: !_isScrolling ? next : null,
          );
    }
```

It happens if you set `showBackButton = true` with `showNextButton = false` (maybe there are another combinations of buttons that show this same effect, only tested this one)

because the row containing the dots and buttons passes from a state with only the dots, from one with dots and a button.

There are some ways to solve the jump on the y axis 1- setting the `crossAxisAlignment: CrossAxisAlignment.end` on the row ->it causes this type of visual:
![image](https://user-images.githubusercontent.com/57464965/211031053-8cacb7e2-fa07-42f2-a837-c0acb101f6ad.png)
2- making the row already count the height of the buttons on these sizedboxes on lines 556 and 578:
```
Expanded(
  flex: widget.skipOrBackFlex,
  child: leftBtn ?? const SizedBox(),
),
```

```
Expanded(
  flex: widget.nextFlex,
  child: rightBtn ?? const SizedBox(),
),
```

**Comment by Macacoazul01** [comment]
The first one is the easier and 'uglier', the second one will be more expensive in time (and probably flutter resources)

**Comment by Macacoazul01** [comment]
Do you have any idea on how to fix this?

**Comment by ghenry** [comment]
Sorry, I thought this was related to the footer in #157

**Comment by Macacoazul01** [comment]
No
I'm gonna reopen the other issue, ok?
The dots and footer issues are different

**Comment by Macacoazul01** [comment]
*can you please reopen #155?

**Comment by Macacoazul01** [comment]
If you approve and merge #158, you can close this issue!
It'll fix the sample app
