### ISSUE TITLE
Accessing the page controller

### ISSUE THREAD

**Issue by ehosseini** [Pyozer/introduction_screen#16]
Can the controller be accessed to move to a certain page on a button click for example?

**Comment by On365** [comment]
Hello, I also need this, I would like to click on a button to go to the next screen. it's possible?

**Comment by Pyozer** [comment]
Hi, I released v1.0.8.
You can now add a `GlobalKey<IntroductionScreenState>` to access to the controller or some public function like `animateScroll(int page)`
