### ISSUE TITLE
Enhancement: New dotsDecorator type

### ISSUE THREAD

**Issue by guyluz11** [Pyozer/introduction_screen#161]
**Is your feature request related to a problem? Please describe.**
I would love to have another (new) type of page navigation decorator which is not dots.

**Describe the solution you'd like**
Specifically I am searching for something at the top that shows the pages the user in
![image](https://user-images.githubusercontent.com/9304740/215316945-9f5a94c0-cffd-4734-850e-27dee0804eb1.png)

**Describe alternatives you've considered**
I am considering using this package https://pub.dev/packages/introduction_story but it is not popular enough.
Also considered creating the top part manually inside of the widgets.
But it will not animate between pages and I think it will be wiser for that to be part of the package so that everyone can enjoy it.
Sometimes designers prefer another option and that one is common in introduction screens.

**Additional context**
Another similar option is to have bars with spacing between them 
![image](https://user-images.githubusercontent.com/9304740/215317178-c79eac1a-feaa-43ba-be12-9eddde122268.png)

**Package version or git hash**
- Version of IntroductionScreen [e.g. 3.1.4]

**Comment by ghenry** [comment]
Sound a likes a nice choice for our users. Fancy having a go and submitting
a pull request? Have a look at how the story app does it?
