### ISSUE TITLE
Enhancement: More options for navigation buttons style

### ISSUE THREAD

**Issue by guyluz11** [Pyozer/introduction_screen#162]
**Is your feature request related to a problem? Please describe.**
Found out that there is one type of navigation button for this package, and I would love to have more options out of the box.

**Describe the solution you'd like**
I would like to have more navigation buttons out of the box that can take more space off the screen and stand out.
The current buttons are small at the side of the screen and can be missed by elderly users.

**Describe alternatives you've considered**
Creating the buttons and the navigation as part of the widget itself, and is not a bad choice just something that can benefit all the users of this package.

**Additional context**
It will replace the space of the dots indicator, if users wish to have a visual representation of the page one possible option can be a navigation indicator at the top as I have suggested in #161.
![image](https://user-images.githubusercontent.com/9304740/215318871-f9ba1064-8066-40e6-bd39-147e89f2d35a.png)

**Package version or git hash**
- Version of IntroductionScreen [e.g. 3.1.4]

**Comment by Macacoazul01** [comment]
@guyluz11 today it's possible to add a custom button, but not replacing the dots...

To separate the case, the custom button is a problem or only the "dots"?

**Comment by guyluz11** [comment]
The problem is that the button can't take most of the bottom part.

So option is to remove the dots and make the button expend to take its place.

**Comment by Macacoazul01** [comment]
@guyluz11 can you test #167 and see if it helps?

**Comment by guyluz11** [comment]
If the customProgress is empty sized box how does the button looks, can you take a picture of it?, does it spreads to take all the remaining space if we give it `width: double.infinity` ?.

**Comment by Macacoazul01** [comment]
You don't need to add an empty sized box as a customProgress as the widget used on the dots is defined (now) as this:
```
widget.customProgress ??
    (widget.isProgress
        ? Semantics(
            label:
                "Page ${_currentPage.round() + 1} of ${getPagesLength()}",
            excludeSemantics: true,
            child: DotsIndicator(
              reversed: widget.rtl,
              dotsCount: getPagesLength(),
              position: _currentPage,
              decorator: widget.dotsDecorator,
              onTap: widget.isProgressTap &&
                      !widget.freeze
                  ? (pos) =>
                      animateScroll(pos.toInt())
                  : null,
            ),
          )
        : const SizedBox()),
```

you just need to set `isProgress` = false (and not define a `customProgress`) to have an empty sized box

You can format the space it will occupy using `dotsFlex` and the other flexes (skip, done, back...)

Set the ones you don't wanna use to 0

**Comment by guyluz11** [comment]
That might help for my case, will test it maybe at Sunday :)

**Comment by Macacoazul01** [comment]
or setting all of these to false/true depending on your use case:
showBackButton
showSkipButton
showDoneButton
showNextButton
