### ISSUE TITLE
Is there a way to remove the dots if we have text field on introduction screen?

### ISSUE THREAD

**Issue by milindgoel15** [Pyozer/introduction_screen#168]
Currently, i have used raw pages and used a column widget to write a form which has a text field and some buttons. Right now, when the keyboard pops up, the dots come up on front of text field which kinda ruins the UI. Is there a way to change that when keyboard is up, the dots should not show or stay below the pages view?

![image](https://user-images.githubusercontent.com/45682747/220899751-39de327a-a443-4118-a7e3-bd525d4a6f4d.png)

**Comment by milindgoel15** [comment]
replying to myself since this repo feels like a dead end.

For anyone wondering how to achieve this, look at this: (first method works a charm)
https://flutteragency.com/detect-keyboard-open-close-in-flutter/

**Comment by Macacoazul01** [comment]
You could try implement this here instead of just complaining

**Comment by Macacoazul01** [comment]
@Pyozer added a PR to try solving this one

**Comment by milindgoel15** [comment]
> You could try implement this here instead of just complaining

A simple reply would have been appreciated that it's not possible to do something like this right now or say like you could try something and add a PR if it works. 

But no, no one bothered to comment single word about it and now that I closed the issue after struggling for a week, you all are now attacking me. Wow genius bro

**Comment by Macacoazul01** [comment]
I'm not a moderator or something like this (and who is attacking you?)

**Comment by Macacoazul01** [comment]
> A simple reply would have been appreciated that it's not possible to do something like this right now or say like you could try something and add a PR if it works.

> But no, no one bothered to comment single word about it and now that I closed the issue after struggling for a week,

Maybe henry didn't had time last week as neither did I. 

He Isn't activelly maintaining the package, just reviewing PRs so everything that is new is being developed by us, users.

The way you replied to your first message and to mine just looks like the maintainer of the package is obliged to be available 24/7 to solve problems.

You already had the solution (so much so that I used your link to implement the PR), so I just said that instead saying things like these:
>since this repo feels like a dead end.

You could implement it the same way as I did

**Comment by Macacoazul01** [comment]
And instead of complaining now about my answer, if you can, please check if this https://github.com/Pyozer/introduction_screen/pull/171 will solve your problem.

If not i'll try to improve it when I have more free time

**Comment by milindgoel15** [comment]
I'm not saying maintainers/developers of this package are obliged to answer and should be available 24*7 to the users. 

First reply was because the repo felt like dead because no one replied. That's why I posted a solution for anyone to face the same issue and get his problem fixed. 

Second, the minute I closed the issue, the owner of this package gave a like to the comment that has the solution to this problem. At this point, anyone will feel they were ignored and should resort to themselves to find solutions. 

Third, creating a PR wasn't my first thought when I found the solution. It never came into my mind to create a PR when we were ignored till the closure of the issue. At that point, fixing my app issue was my first priority and also fix other issues as well which still are there.

If he was really inactive, then sure apologies for saying dead repo.

Apologies to you as well. Thanks for your pr tho.

**Comment by Macacoazul01** [comment]
@ghenry any release date for this one?

**Comment by ghenry** [comment]
I've actually meant to do this last week but got distracted. Will do today.
Thanks for your patience.

**Comment by Macacoazul01** [comment]
Tks!

**Comment by Macacoazul01** [comment]
@milindgoel15 you can now use 3.1.7
