### ISSUE TITLE
Enhancement: Add support for larger font size

### ISSUE THREAD

**Issue by rosenpin** [Pyozer/introduction_screen#169]
**Is your feature request related to a problem? Please describe.**
The intro screen doesn't work well with larger font size (if set by the user in the device settings).  
This leads to the body portion of the screen to be cut off:

![image](https://user-images.githubusercontent.com/5289630/221183168-8ff87610-2553-49fa-9408-260ac0b20ecb.png)

**Describe the solution you'd like**
The intro screen should not cut off the body part. Instead, it should either allow the user to create custom screens for different font/display sizes the consider this space limitation or it should shrink the image portion of the intro to allow for the extra space

**Package version or git hash**
- Version of IntroductionScreen [3.0.2]

**Comment by ghenry** [comment]
Pull requests welcome!

**Comment by Macacoazul01** [comment]
@rosenpin this is a problem of the flex that you set for the body and content.

If the body is bigger than the actually screen size it will turn into a scroll view
