### ISSUE TITLE
Set pageColor not working

### ISSUE THREAD

**Issue by frankenten13** [Pyozer/introduction_screen#17]
Hi, i try add pageColor: Colors.transparent but not working, can you fix it. Thanks

**Comment by Pyozer** [comment]
Hi, I tried using the example code of this package and it works fine.
I defined a color in the canvasColor property of the theme of my MaterialApp, and I defined pageColor with Colors.transparent (or even just removed the pageColor property), and it works.

Can you show me your code?

**Comment by frankenten13** [comment]
I put my backgournd image in Stack, but  not working, can you help me.

```
const pageDecoration = const PageDecoration(
      titleTextStyle: TextStyle(fontSize: 28.0, fontWeight: FontWeight.w700),
      bodyTextStyle: bodyStyle,
      descriptionPadding: EdgeInsets.fromLTRB(16.0, 0.0, 16.0, 16.0),
      pageColor: Colors.transparent,
      imagePadding: EdgeInsets.zero,
    );
```

```
return Stack(
      children: <Widget>[
        Container(
          child: _buildImage('img1'), <-- My Background
        ),
        IntroductionScreen(
          key: introKey,
          pages: [
            PageViewModel(
              title: "Fractional shares",
              body:
              "Instead of having to buy an entire share, invest any amount you want.",
              image: _buildImage('img1'),
              decoration: pageDecoration,
            ),
           PageViewModel(),
           PageViewModel(),
          ....
```

**Comment by Pyozer** [comment]
Hello @frankenten13, sorry I've just seen your reply.. 1year later :/
I hope you find the solution ^^
On my first reply I forgot that there is a param `globalBackgroundColor`. By settings `Colors.transparent` you will have a full transparent IntroductionScreen, so you can set an image as background, like your previous code.
