### ISSUE TITLE
Bug: After each page slide the focus is requested by introduction slides

### ISSUE THREAD

**Issue by RobinVerheijen** [Pyozer/introduction_screen#172]
Hi Pyozer,

First of all thanks for the plugin, great work!

The only problem I have is that when a slide changes the plugin requests focus which results in the focus being removed from for example a textfield.

This is quite annoying, can you please look into this?

Thanks in advance!

**Comment by ghenry** [comment]
Hi @RobinVerheijen 

@Pyozer not longer maintains this, I do. I recommend having a look at this yourself and submitting a PR for any feature or bug fix you require. 

I'll happily review it and release it.

Thanks for your time,
Gavin.

**Comment by Macacoazul01** [comment]
> The only problem I have is that when a slide changes the plugin requests focus which results in the focus being removed from for example a textfield.

@RobinVerheijen when you slide from one screen to another?

If so, the focus shouldn't be maintained as the textfield isn't being presented anymore (or am I missing something?).

Can you add a sample code/video to show the problem?
