### ISSUE TITLE
Bug: The dots progress hides behind the navigation bar on android

### ISSUE THREAD

**Issue by milindgoel15** [Pyozer/introduction_screen#173]
**Describe the bug**
By default, the progress indicator draw behind the navigation bar on android. That is, only with 3 button nav bar and 2 button gesture system.  

**To Reproduce**
1. Write a simple introduction screen and run on android with 3 or 2 button nav
2. Progress indicator draws behind

**Expected behavior**
It should avoid drawing behind the nav bar and detect the height of nav bar in either of the nav style of android and draw above it.

**Screenshots**
![image](https://user-images.githubusercontent.com/45682747/232766381-ac82f12b-312f-44ad-bcd3-e2ba0b632b8c.png)

**Smartphone (please complete the following information):**
- Device: Android Emulator 1080x2400
- OS: Android 13
- Version 3.1.17 of introduction screen

**Additional context**
n/a

**Comment by Macacoazul01** [comment]
This still happens if you put introduction_screen into a SafeArea widget?

**Comment by milindgoel15** [comment]
oh that worked

**Comment by Macacoazul01** [comment]
Gonna launch an update with this as an optional parameter (if it isn't already on the code and I didn't notice)

**Comment by milindgoel15** [comment]
yea without the safe area, if i provide the bottom spacing to dotsDecorator as `MediaQuery.of(context).padding.bottom == 0 ? 0.sp : 50.sp,` that works as well.

**Comment by Macacoazul01** [comment]
I'm not sure what the safeArea widget does behind the curtains, but maybe it's something like your code

**Comment by Macacoazul01** [comment]
@milindgoel15 added #174

**Comment by ghenry** [comment]
Looks good! Just re-running CI then will merge and do a release tonight. Thanks!
