### ISSUE TITLE
Bug: showBottomPart not hiding bottompart

### ISSUE THREAD

**Issue by shayant98** [Pyozer/introduction_screen#182]
**Describe the bug**
When setting showbottompart to false it still shows a white indent at the bottom

**To Reproduce**
1. Set showBottomPart to false
2. See error

**Expected behavior**
Pagecolor should take whole screen when showBottomPart is set to false

**Additional context**

**Comment by Macacoazul01** [comment]
Show bottom part isn't used to define margins, it's used to show the dots. 
Can you send a sample code and print?

**Comment by ghenry** [comment]
v3.1.9 released.
