### ISSUE TITLE
Enhancement: Infinite scroll

### ISSUE THREAD

**Issue by meidikawardana** [Pyozer/introduction_screen#184]
**Is your feature request related to a problem? Please describe.**
When I set `autoScrollDuration`'s value to 2000, I realize the scroll can only happen once. Because there is no feature to make it to first page and continue scrolling infinitely

**Describe the solution you'd like**
With autoScrollDuration set, I think it's logical to also provide isInfiniteScroll parameter, which should allow the autoscroll to go back to first page automatically. The parameter also useful for manual scroll, to allow us to go back to first page when we scroll on the last page.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Package version or git hash**
- 3.1.8 (latest when this feature request was written

**Comment by Macacoazul01** [comment]
If i could understand the request right, to achieve this it would be necessary to:
add the infinite scroll parameter
change the function that scrolls to go back to the first page after it reaches the last

I'm not able to change this right now, but you can send a PR to @ghenry review

**Comment by Macacoazul01** [comment]
like there are already two PRs related to the auto scroll waiting for his review, if you can, please merge them to your fork before sending yours

**Comment by Macacoazul01** [comment]
@meidikawardana added on #186
waiting for @ghenry check and merge

**Comment by ghenry** [comment]
Commented on PR.

**Comment by ghenry** [comment]
Are we waiting for a new release to close this?

Thanks.

**Comment by Macacoazul01** [comment]
Yes

**Comment by ghenry** [comment]
v3.1.9 released.
