### ISSUE TITLE
scroll physics

### ISSUE THREAD

**Issue by Poker-Face-Vii** [Pyozer/introduction_screen#19]
I think it would be better to change physics in pageView to **AlwaysScrollableScrollPhysics** instead of **BouncingScrollPhysics** Or at least it would be great if scroll physics be more modifier than just freeze.

Thanks For Your Awesome library

**Comment by Pyozer** [comment]
Hi, sorry for late response..
Yeah it's could be great to have property `physics`. I set `BouncingScrollPhysics ` to avoid having ripple effect on side when scroll.
You can make a pull request if you want. I will try to do it soon.
