### ISSUE TITLE
Bug: The default dot decorators are not animating on 3.1.9.

### ISSUE THREAD

**Issue by milindgoel15** [Pyozer/introduction_screen#190]
**Describe the bug**

The dots progress which is used to animate when moving between pages. But as of 3.1.9, they are static and not animating. On 3.1.8, it's fine.

**To Reproduce**
1. Use 3.1.9 and make some sample 2 or 3 pages,
2. Move between pages and dots progress wont animate but jump.

**Expected behavior**

Dots progress animates properly

**Screenshots**

On 3.1.8:
https://github.com/Pyozer/introduction_screen/assets/45682747/e0cb056b-89e7-4785-ae53-c228eea410ad

On 3.1.9:
https://github.com/Pyozer/introduction_screen/assets/45682747/0b5bcedd-82b4-4a01-93b3-d7375f8a1fb5

**Smartphone (please complete the following information):**
- Device: Xiaomi 11 Lite NE 5G
- OS: Android 13

**Additional context**

**Comment by Pyozer** [comment]
Hi, I've not checked, but seems to be the migration of double to int type, of current page variable..
The animation of dots need a double, now it's an int so page animation is now 0 -> 1 and before was 0, 0.1, 0.2, .., 1

**Comment by Pyozer** [comment]
New version v3.1.10 fix that ;)
