### ISSUE TITLE
Bug: Problem with infinite AutoScroll property: true and navigation outside of onboarding screens

### ISSUE THREAD

**Issue by amed901107** [Pyozer/introduction_screen#191]
when using these library properties the following error occurs when going to the next screen after onboarding
 allowImplicitScrolling: true,
      autoScrollDuration: 3000,
      infiniteAutoScroll: true,
After so many tests, the conclusion is reached that it is the property    infiniteAutoScroll: true  that causes the error
E/flutter (  873): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 105 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter (  873): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (  873): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (  873): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:105:12)
E/flutter (  873): #3      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:193:41)
E/flutter (  873): #4      IntroductionScreenState._movePage (package:introduction_screen/src/introduction_screen.dart:481:31)
E/flutter (  873): <asynchronous suspension>
E/flutter (  873): #5      IntroductionScreenState._autoScroll (package:introduction_screen/src/introduction_screen.dart:450:11)
E/flutter (  873): <asynchronous suspension>
E/flutter (  873): 

Flutter: 3.10.5
OS: Android 12
Phone: Xiaomi Redmi Note 11 Pro MUI Global 13.0.2

**Comment by docaohuynh** [comment]
I got same error when set infiniteAutoScroll: true

**Comment by Pyozer** [comment]
Version 3.1.13 fix this issue
