### ISSUE TITLE
Bug: last page not detected on Nexus 10 (emulator)

### ISSUE THREAD

**Issue by bobab12** [Pyozer/introduction_screen#192]
**Describe the bug**

While testing on a Nexus 10 (API 33) emulator I noticed that I was unable to pass the introduction screen with three pages. While moving to the last page, the value of `IntroductionScreenState._currentPage` did not pass `1.99999999999996`, thus failing the following condition:

`final isLastPage = (_currentPage == getPagesLength() - 1);`

This can be corrected by rounding the _currentPage value. This will also change the next button into a done button while animating between the last pages, which appears nice IMO.

`final isLastPage = (_currentPage.round() == getPagesLength() - 1);`

**Smartphone (please complete the following information):**
- Device: Nexus 10 API 33 emulator
- OS: Android
- Version: 13.0

**Comment by Pyozer** [comment]
Hi, thank you for your issue !
Maybe introduced in the latest release, I will merge your PR and publish a new release ;)

**Comment by tommienu** [comment]
I can confirm this bug when using three pages.
