### ISSUE TITLE
Enhancement: Add a keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag, to the scrollview

### ISSUE THREAD

**Issue by Tristannos** [Pyozer/introduction_screen#195]
The user needs to fill in multiple textFields and so if the keyboard is open half of the screen space is taken up. Everywhere else i have this enabeld.

The options to enable :  keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag,

I tried adding my own singlechild scrollview, but with no succes. !hasSize error.

Thankyou!

Version: 3.1.11

**Comment by Pyozer** [comment]
In new version 3.1.13, you can set `scrollViewKeyboardDismissBehavior` parameter in PageViewModel
