### ISSUE TITLE
PageController.page cannot be accessed before a PageView is built with it.

### ISSUE THREAD

**Issue by Obada2020** [Pyozer/introduction_screen#199]
Unhandled Exception: 'package:flutter/src/widgets/page_view.dart': Failed assertion: line 170 pos 7: 'positions.isNotEmpty': PageController.page cannot be accessed before a PageView is built with it.

**Comment by SupianIDz** [comment]
I experienced it too.

**Comment by syedarsalankazmi** [comment]
getting the same error.

`Unhandled Exception: 'package:flutter/src/widgets/page_view.dart': Failed assertion: line 170 pos 7: 'positions.isNotEmpty': PageController.page cannot be accessed before a PageView is built with it.`

**Comment by fedejuret** [comment]
Same error here

**Comment by domhandy** [comment]
I am getting this error on Skip and Done.

**Comment by domgolonka** [comment]
I am getting this error on skip and done.

**Comment by fedejuret** [comment]
> I am getting this error on skip and done.

I managed to "solve it" by eliminating autoplay. That the user has to tap on "next". 
And I also had to remove the "skip" button.

**Comment by Pyozer** [comment]
New version 3.1.13 fix that issue.
