### ISSUE TITLE
Minor improvements questions

### ISSUE THREAD

**Issue by Nalsos** [Pyozer/introduction_screen#2]
Hello Jean I like the simplicity of your library 

but I was wondering if it was possible to 
Iset the image optional, on the pageviews.

and then make it possible to override the default skip action, for instance if I wanted to skip to the next screen instead of the next pageview.

**Comment by Pyozer** [comment]
@Nalsos I created a branch `dev-optionalimage-onskip`, can you test if it's what you expected ?
(You can specify this git repo with a specific branch in your pubspec.yaml)

**Comment by Nalsos** [comment]
Awesome I will try it out and get back to ya

**Comment by Pyozer** [comment]
@Nalsos Today I merge the branch `dev-optionalimage-onskip` and made an update of the package. So you can simply change the version to `1.0.0` in your pubspec.yaml.

**Comment by Nalsos** [comment]
It works very well @Pyozer and like I expected although I was wondering since it seems like you changed the pageview to rewuire 2 arguments instead of 3 like with the picture, is it still possible to set it up like in your previous example with this current version or have my silly suggestion ruined it for someone that might want to make use of your library as it was in version 0.0.5 ??

**Comment by Pyozer** [comment]
Hi, sorry I didn't see your message.
Yes it's still possible to use it like before. I just set the image parameter in optional.
