### ISSUE TITLE
Enhancement: Publish a new version of this package (tech debt conflicts)

### ISSUE THREAD

**Issue by istornz** [Pyozer/introduction_screen#211]
It would be awesome to release a new version of this plugin since dependencies was updated [2 months ago](https://github.com/Pyozer/introduction_screen/commit/c3fbdf9b610772cbaacede3339787b71b6a8dbfd).

A lot of package has upgraded the **flutter_keyboard_visibility** dependency to latest major version (v6.0.0). This plugin block the upgrade process of the other :/

Example of conflicted plugin: **flutter_typeahead** 

Thanks for the awesome package 👍

**Comment by Pyozer** [comment]
Version 3.1.13 available, sorry for the delay :/

**Comment by istornz** [comment]
Thanks @Pyozer 🙏
