### ISSUE TITLE
Overflow on dot indicator for more than 5 pages

### ISSUE THREAD

**Issue by XSiyabonga** [Pyozer/introduction_screen#22]
The dot indicator overflows in pixels when there are more than 5 pages.

**Comment by Pyozer** [comment]
Hi,
I known.. I will try to check this soon but I'm very busy :/
You can make a pull request if you want ;)

**Comment by sargntpi** [comment]
> The dot indicator overflows in pixels when there are more than 5 pages.

You probably have it sorted but I fixed this by setting a flex of 0 for the skip/done buttons and 2 for the dots indicator. Could probably up it more if need be but that worked for me with 7 pages.
