### ISSUE TITLE
Disable the "back" button on HomeScreen After clicking "done" on the Intro page.

### ISSUE THREAD

**Issue by vengatesh-ssrv** [Pyozer/introduction_screen#25]
Disable the "back" button on HomeScreen After clicking "done" on the Intro page.(Disable the "back" option redirection to the intro page)

**Comment by aaqibism** [comment]
In the example, their _onIntroEnd function was as follows:
` Navigator.of(context).push(
      MaterialPageRoute(builder: (_) => HomePage()),
    );`  
However, if you don't want the user to be able to click the back button and return to the intro then the function should instead be:
` Navigator.of(context).pushReplacement(
      MaterialPageRoute(builder: (_) => HomePage()),
    );`  
This will correctly pop the Introduction screen and push your HomeScreen.
