### ISSUE TITLE
How do I scroll to the next page when I press the next button I created?

### ISSUE THREAD

**Issue by son** [Pyozer/introduction_screen#26]
Thanks for the nice library.

I want to link my own Next button with the Introduction Screen.
Therefore, I want to use `_onNext` () of `IntroductionScreenState`, but it is private.
Is there any other way?

**Comment by Pyozer** [comment]
Hi, thank you ;)
I will update the package with onNext in pubic

**Comment by mikekosulin** [comment]
@son you can do this with globalKey.

add this to state:
```dart
final _introKey = GlobalKey<IntroductionScreenState>(debugLabel: '_introScreenKey');

void _nextPage() {
    _introKey.currentState.controller.nextPage(duration: Duration(milliseconds: 250), curve: Curves.easeIn);
}
```

**Comment by son** [comment]
Thank you!
