### ISSUE TITLE
Intro Screen should just open first time when opening app not everytime.

### ISSUE THREAD

**Issue by 1AnkitSingh02** [Pyozer/introduction_screen#27]
Introduction screen is very awesome but the thing is it should just be there only once when we open app first time.
So, I made a splash screen and used dart async to find intro screen is opened or not , it worked fine.
If you could provide that feature in this package it would be helpful a lot.
Thank You.

**Comment by Pyozer** [comment]
Hi, thank you 🙏 

I don't think it's to this package to handle this. For me it's the app that should manage whether or not display the IntroductionScreen.
What you're doing is great, in my apps, I made also a splashscreen in Flutter (with exactly the same design as native splashscreen, so no visible transition), load sharedpreferences and few others things. If the user has already seen the Introduction, I skip it and launch HomeScreen directly. I also add a button in the app to see the Introduction again.

Each app implement the package differently, if I add it directly into the package, it can be bad for some app.

**Comment by 1AnkitSingh02** [comment]
Thank you for your reply. I understand it that you can't implement in it. Thanks.
