### ISSUE TITLE
Page states not saving

### ISSUE THREAD

**Issue by OpticNectar** [Pyozer/introduction_screen#28]
If you have form fields in the `PageViewModel` they do not save state when going between the pages. For this to work `IntroPage` needs to be a `StatefulWidget` and `AutomaticKeepAliveClientMixin` needs to be used.

**Comment by Pyozer** [comment]
Hi ;)
Thanks for your issue, I've just commit a fix. It will be available on next update (very soon).
Sorry for late reply :/

**Comment by Pyozer** [comment]
Pages states are now saved in release `2.1.0` 🎉
