### ISSUE TITLE
Can i use video at image parameter?

### ISSUE THREAD

**Issue by josemauromani** [Pyozer/introduction_screen#30]
Can i use a video player at image parameter of PageViewModel ? 
`PageViewModel(
title: 'TitleExample',
body:'Text example',
image: VideoPlayerController.asset('assets/videos/presentation.mp4'),
),`

**Comment by SalahAdDin** [comment]
@josemauromani Is it possible?

**Comment by SalahAdDin** [comment]
@Pyozer Is it possible?

**Comment by Pyozer** [comment]
Hello @josemauromani (sorry for very late reply), @SalahAdDin ;)

Yes it is possible. The Image parameter expect a `Widget`, so you can provide any Widget, like a video, image, even a Google Maps (not tested by should work ^^).
I just tested to be sure with the [video_player](https://pub.dev/packages/video_player) package, and it works fine ;)

I close this issue, if you have any questions, re-open it.
