### ISSUE TITLE
Images not opening in Linux Desktop

### ISSUE THREAD

**Issue by xpat** [Pyozer/introduction_screen#31]
Thanks for the introduction screen code.  I couldn't get the images to appear when I ran the code using $flutter run -d linux.  With the same codebase, I ran $flutter run -d chrome and the images do appear in the web version.  I opened an issue in Flutter:

https://github.com/flutter/flutter/issues/62269

**Comment by Pyozer** [comment]
Sorry for late reply.
I close this issue, on the flutter issue you mentioned, seems working on linux.
