### ISSUE TITLE
how to show onboard screens only once  

### ISSUE THREAD

**Issue by Sreejithtechno** [Pyozer/introduction_screen#37]
i just want to show only once install app after. every time i am opening it show on board screen. how to disable that?

**Comment by benyaminbeyzaie** [comment]
you must save a parameter in shared preferences of your app and every time user opens app you must check if user ever seen the intro screen or not! use this link for more information: https://stackoverflow.com/questions/50654195/flutter-one-time-intro-screen

**Comment by Pyozer** [comment]
Hi ;)
I close this issue. Like said @benyaminbeyzaie and in the stackoverflow post, you can use shared_preferences package.
