### ISSUE TITLE
Onboard screen shows up, every time the user has viewed once.

### ISSUE THREAD

**Issue by ameysunu** [Pyozer/introduction_screen#38]
As per convention, the user is supposed to see the onboard only once, when the app loads for the first time and never after that. But this introduction screen keeps showing every time the app is launched.

**Comment by danielSafeNow** [comment]
Because this is not the responsibility of the package. 
You could e.g. use the [shared_preferences package](https://pub.dev/packages/shared_preferences) to store wether the user has already seen this intro screen or not.

**Comment by ameysunu** [comment]
Yeah, I know that but it would be a little more seamless if this package had Shared Preferences inbuilt.

**Comment by Pyozer** [comment]
I close this issue, like @danielSafeNow said, it's not responsibility of this package to do this.
For example, you can display it on first start, but also after if user want to see it again (using a button on your app).
