### ISSUE TITLE
Dot Color for inactive progress indicator

### ISSUE THREAD

**Issue by mordeccai** [Pyozer/introduction_screen#4]
Just a minor issue but I would like `dotColor` which is present in `DotsIndicator` widget to be available through `IntroductionScreen`'s parameters. This will help those like me who want to change the color of the dots that are not active

**Comment by Pyozer** [comment]
Hi ;)

Thank you for your report, I forget that property..
I will made an update to fix this soon ;)

**Comment by Pyozer** [comment]
@mordeccai I published an update of this package, you can move to v1.0.4. I also fix layout issue and you can now also provide flex parameters (for skip, dots and next/done button).
