### ISSUE TITLE
Curve parameter not working

### ISSUE THREAD

**Issue by marcqtan** [Pyozer/introduction_screen#41]
I've tried using the curve parameter but it seems that it's not being applied? The animation is still the same when changing the page.

Sample code:

```
    IntroductionScreen(
        curve: Curves.bounceOut,
        pages: pages(),
        done: Text('Done'),
        onDone: () {},
      ),
```

**Comment by Pyozer** [comment]
Hello ;) Sorry for my very late reply :/
I just checked and tried and it seems to work.
I tried with `Curves.elasticOut` and the animation changed correctly.

I close the issue, if you still have the problem, reopen it.
