### ISSUE TITLE
Custom footer

### ISSUE THREAD

**Issue by paulkagiri** [Pyozer/introduction_screen#43]
Great work on this library, my suggestion would be to make this part customizable:
https://github.com/Pyozer/introduction_screen/blob/master/lib/src/introduction_screen.dart#L246-L278 such that it's possible to have very custom widgets for that part.

**Comment by Pyozer** [comment]
Hi ;) Sorry for very late reply.
I've just merge a PR #61  to have a customFooter on pages, is same thing you asked ?
