### ISSUE TITLE
Right to Left Behaviour

### ISSUE THREAD

**Issue by emadomedher** [Pyozer/introduction_screen#47]
thanks for the solid package, works wonderfully here. Was wondering if you can add RTL behaviour where the pages scroll to the right not to the left and reverse the location of next/end buttons. Also I could do the PR with some pointers 👍 

thanks

**Comment by Pyozer** [comment]
Hi @emadomedher,
It was not in my priorities to be honest, but I will add it in next release, it's not many changes (PageView already support reverse/RTL), it just need a change in [dots_indicator](https://github.com/Pyozer/dots_indicator) sub-package I think.

Thanks for your issue ;)

**Comment by Pyozer** [comment]
RTL support added in release `2.1..0` 🎉
