### ISSUE TITLE
Background color for all Pages

### ISSUE THREAD

**Issue by pascalf22** [Pyozer/introduction_screen#5]
Hello @Pyozer ,

Wonderful work ! I love it ! 
I have 2 questions,

The first one is, is it possible to have a backgroundcolor or background image for all PageViewModel...?
I try to place the IntroductionScreen() in a container with a backgroundimage or background color and i set the PageColor to Colors.Transparent for all PageViewModel,
But the background is still white !

Is it possible ?

Also, my second question, is it possible to hide the next button and Done button ? 
the same as showSkipButton: false,

Thanks a lot ! 

Pascal

**Comment by Pyozer** [comment]
Hi @pascalf22 and thank you !

With the current version, it is not possible to have a transparent background (because it is wrapped with a Scaffold), but I can add this if you want.
For the "Next" button, I can also add it in the next update.

Thanks for the feedback.

**Comment by Pyozer** [comment]
@pascalf22 You can update the package to `1.0.5+1`. I've added `globalBackgroundColor` and `showNextButton` property ;)

**Comment by pascalf22** [comment]
Hello @Pyozer !

Ho thanks a lot !! I'm happy to read it !!
That is perfect !! I will test it in the next day !!

I'm very very very happy !! Thanks a lot !
I wish you a great day !!

Thanks a lot !

Pascal

**Comment by Nengha-John** [comment]
Hello, thank you for all the comments, I tried going through all of them but have not found what am looking for. I'm trying to set a full background color for individual pages but the bottom part seems to have a different color. I tried setting showNextButton etc to false but it doesn't seem to work. Is there any way to set full page background color for individual pages?
![Screenshot_20221108-105958](https://user-images.githubusercontent.com/68301183/200507779-98bd0f94-eab8-45ad-8597-fc7fa19026c9.png)

**Comment by pascalf22** [comment]
Hello !
Thanks for the message! I'm sorry i can't help you because i'm not using Flutter for anymnore (for now) so i have no skill in Flutter...

I'm sorry again ! Try To ask a question on StoackOverFlow...
Thanks! I hope someone can help you
Have a great day !

________________________________
De : Nengha ***@***.***>
Envoyé : 8 novembre 2022 03:04
À : Pyozer/introduction_screen ***@***.***>
Cc : pascalf22 ***@***.***>; Mention ***@***.***>
Objet : Re: [Pyozer/introduction_screen] Background color for all Pages (#5)


Hello, thank you for all the comments, I tried going through all of them but have not found what am looking for. I'm trying to set a full background color for individual pages but the bottom part seems to have a different color. I tried setting showNextButton etc to false but it doesn't seem to work. Is there any way to set full page background color for individual pages?
[Screenshot_20221108-105958]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F68301183%2F200507779-98bd0f94-eab8-45ad-8597-fc7fa19026c9.png&data=05%7C01%7C%7C8cb34cf54bf54f47c41108dac15fda2a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638034914667548232%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Gy3Rf69zyW3uIssefkN%2BYUTlgSxXyfIFqsIhiKc2PR4%3D&reserved=0>

**Comment by Nengha-John** [comment]
Thank you for the reply. After a deep research I found a way to create what
I was looking for using rawPages[].BTW thank you for a great package and
all the best in your next stack.
