### ISSUE TITLE
Go to previous page without scrolling - Back Button

### ISSUE THREAD

**Issue by kasten4444** [Pyozer/introduction_screen#51]
How can I get to the previous page without swiping?

**Comment by Pyozer** [comment]
Hello, I hope you have found the solution.
I suppose that you want to display a back button ?
You can't add a real back button, but you have 2 options.

### Replace the skip by a back button

Define a GlobalKey, like this (check example app):
```dart
final introKey = GlobalKey<IntroductionScreenState>();
```

Set the `key`, `skip` and `onSkip` params of IntroductionScreen like this:
```dart
key: introKey,
skip: const Text('Previous'),
onSkip: () {
    final currentPage = introKey.currentState?.controller.page ?? 0.0;
    introKey.currentState?.animateScroll(currentPage.toInt() - 1);
    // In next release do this:
    // introKey.currentState?.previous();
}
``` 
The only downside is that on the last page, the button will not be displayed.

### Add a global footer

In next release (very soon available), you will be able to set a globalFooter, display below controls/dots.
So it will be possible to display a back button. Set the onPress of button like the onSkip of previous option.

### Bonus

Like you see in comment of code example above, in next release I will add a `previous()` public function, like there is a `next()`.

I close this issue, if you have any other questions on this issue, re-open it ;)

**Comment by MiroLiebschner** [comment]
I would like to use a Back-Button on every screen except for the first. 

If I use the footer the Back-Button is below the Dots. 
If I use the Skip-Button solution the Back-Button is on the first screen but not on the last. 

One way I could see is to create the Dots with the footer but this is not a convenient solution and takes a lot away from the value provided by the package. 
Is there a different solution?

**Comment by lucasdidur** [comment]
Could you please reopen?

**Comment by rphly** [comment]
Please reopen! :)

**Comment by Pyozer** [comment]
Hi, I reopen this issue. I will try to see that tomorrow or sunday.

**Comment by Pyozer** [comment]
Sorry for delay, I've merged a PR that add a back button, I close this issue again.
