### ISSUE TITLE
A RenderFlex overflowed by 13 pixels on the right.

### ISSUE THREAD

**Issue by raghavan-mookiah** [Pyozer/introduction_screen#53]
When we add more pages, the view is scrollable or expanded. Getting the RenderFlex overflowed on Screen
<img width="374" alt="Screenshot 2021-01-19 at 6 24 04 AM" src="https://user-images.githubusercontent.com/47385593/104974781-fa500900-5a1e-11eb-84b5-20d9825e98a1.png">

**Comment by Pyozer** [comment]
Hi, sorry for late :/
You can edit flex ratio of dots and buttons. You can also reduce space between dots.
But I thinks have many pages is not quite good for users.

**Comment by rohitbhoite** [comment]
You can use Expanded widget

**Comment by XSiyabonga** [comment]
> an use Expanded widget

Please expand on how?

**Comment by Beyga** [comment]
Use `dotFlex` parameter.

**Comment by McMainsLiam** [comment]
Changing my `dotsFlex` parameter to 2 fixed the issue for me. Not sure if it'll effect other UI elements like the skip and done buttons, but I'm navigating between all the pages programatically, so it's a non-issue for me. Thanks @Beyga for the tip!

**Comment by Beyga** [comment]
I've already figured it out :)
