### ISSUE TITLE
cannot decrease the space taken by text (increase the area of image height)

### ISSUE THREAD

**Issue by mohadel92** [Pyozer/introduction_screen#54]
HI,
i tried to find any way to expand the image height and decrease the text space portion
but i couldn't find any solution for this issue
any help?

**Comment by MarwanMagdy1295** [comment]
fit: BoxFit.cover,
decoration: PageDecoration(
            imageFlex: 3,
          ),

**Comment by mohadel92** [comment]
Thanks @MarwanMagdy1295 
issue solved
