### ISSUE TITLE
Stop scrolling inside the bodyWidget

### ISSUE THREAD

**Issue by NachiketaVadera** [Pyozer/introduction_screen#56]
I have noticed that the bodyWidget makes that part of the page scrollable. How do we stop this behavior?

**Comment by mirkancal** [comment]
https://github.com/Pyozer/introduction_screen/pull/58

**Comment by Pyozer** [comment]
Thank you for your PR, I will merge it. But I think it's better to keep original behaviour to not break some apps using a scroll. I will just add a param like `useScrollView` (by default `true`).

**Comment by Pyozer** [comment]
PR merged, update on Pub.dev will be very soon available.
I close this issue, if you want to re-open it, do it ;)
