### ISSUE TITLE
null-safety Support

### ISSUE THREAD

**Issue by TomKrauss** [Pyozer/introduction_screen#57]
It would be nice if the plugin would also support for Dart null safety, which is being enforced by upcoming flutter releases. For details, refer to: https://dart.dev/null-safety

**Comment by abhelal** [comment]
required null safety

**Comment by justTOBBI** [comment]
I really like the package, but there is no null safety :(

**Comment by leynier** [comment]
I will make a PR with null safety support implementation

**Comment by Pyozer** [comment]
Hi, sorry for not having answered (not only for this issue) :/
Thank you @leynier for the PR, I will merge it when it's ready with others PR in pending, and try to fix all others issues in same time.

**Comment by Pyozer** [comment]
I just published v2.0.0 with null safety support (PR #60 )
