### ISSUE TITLE
Any chance the description could be a Widget?

### ISSUE THREAD

**Issue by steveroderickIntrohive** [Pyozer/introduction_screen#6]
This is the third Onboarding approach I have tried and is the one I like the most. Great work. 

What I'm trying to accomplish is to have text and icons in the description - so that I could describe things like "Tap the + button to ...." or "Tap the Pencil to do ...", where the + and Pencil are icons / images.

Would this be possible?

Thanks,

Steve

**Comment by Pyozer** [comment]
Hi ;)

Yeah it's a great idea, I could add a new parameter `descriptionWidget` to provide the description as a Widget.
I try to do this soon ;)

Thanks for your feedback !

**Comment by Pyozer** [comment]
Hi @steveroderickIntrohive, sorry I've been too busy... I try to do it today ;)

**Comment by Pyozer** [comment]
@steveroderickIntrohive
Update published 🎉 => `1.0.6`
You can now provide body as Widget with `bodyWidget`, I also do same thing for title with `titleWidget`.

**Comment by steveroderickIntrohive** [comment]
That's awesome! Thank you very much.

Steve
