### ISSUE TITLE
Is there a way to move to the next slide after a certain time. Or access the next() function to do it manually?

### ISSUE THREAD

**Issue by ricardonior29** [Pyozer/introduction_screen#62]
I need that after 5 seconds, the slide change automatically, like in some web banners behaviors

Thanks

**Comment by Pyozer** [comment]
Hi,

You can access to next() function using a key `GlobalKey<IntroductionScreenState>`, check the example app.
IntroductionScreen not have a timing auto-next built-in, so you will need to do it yourself and call next() function using the key.

**Comment by amineboularbah** [comment]
Use
`introKey.currentState.next()`
