### ISSUE TITLE
[proposal] Improve README documentation

### ISSUE THREAD

**Issue by imcrisanto** [Pyozer/introduction_screen#66]
First of all, thank you for your plugin! It was easy to use and gave excellent results :)

I am a native English speaker and I think I can help improve the documentation 

I just sent three pull requests #65  #64  #63  for various typo errors and I decided to stop and just fork the project to help edit the README and Documentation. If you are okay with this I will proceed to edit the text and also the example file to make it easier for others to use as well.

**Comment by Pyozer** [comment]
9 April... sorry for delay :/ 
Thank you for your PRs, I've merged it.

Of course you can help to improve documentation of the project ;)
