### ISSUE TITLE
Trying to add a listener to ScrollController results in error

### ISSUE THREAD

**Issue by WindfallProphet** [Pyozer/introduction_screen#67]
`ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 109 pos 12: '_positions.length == 1'
`

Just trying to access the pixels scrolled: 
`  void _onScroll() {
    print(_scrollController.position.pixels);
  }`

I think I understand the error, but I am curious if it's possible to access the scrollcontroller of one page.

**Comment by WindfallProphet** [comment]
Seems if pages > 1, you get this error. When you only have 1 page, everything is good. 

I'm not sure if the proper solution is to pass the ScrollController onto 1 page via PageViewModel or some alternative.

**Comment by maltebenjamin** [comment]
my fault, im sorry!
i didnt thought about using multiple pages before adding this feature.
should be fixed with #71 now

**Comment by maltebenjamin** [comment]
btw:
for everybody who wants to to use the ScrollController parallelly,
theres a flutter package by google.dev called [linked_scroll_controller](https://pub.dev/packages/linked_scroll_controller).
by this its possible to have synchronous handling of different controller

**Comment by maltebenjamin** [comment]
#71 is merged now, so this should be closed.

**Comment by Pyozer** [comment]
@maltebenjamin Yes, sorry for inactivity :/ I will published new release very soon, need to finish some changes before.
