### ISSUE TITLE
dots position

### ISSUE THREAD

**Issue by NestorDevs** [Pyozer/introduction_screen#68]
is there a way to change the indicator dots? I would like to place them on top of the right end of the `PageViewModel`
for now it is displayed between the footer and the pageview .. is there a way to customize the dots to place them on any surface of the pageview?

![image](https://user-images.githubusercontent.com/36705339/115159437-16386a80-a061-11eb-96e5-b41dc6825207.png)

**Comment by yogithesymbian** [comment]
same, i need change dots position into inset of content , not bottom center .

**Comment by Pyozer** [comment]
Hi, I'm not planned to support this soon, but you can made a PR if you want.
I'm just afraid that it will complicate the package too much :/
