### ISSUE TITLE
[Improvement] Block Skip button from getting focus

### ISSUE THREAD

**Issue by Macacoazul01** [Pyozer/introduction_screen#69]
When i use a focus node for the entire Onboarding widget to change the focus from one textformfield to another, the skip button gets the focus instead of the next textformfield.

The button could have something like the InkWell widget property "canRequestFocus" to block this from happening.

**Comment by Pyozer** [comment]
Hi, sorry for long delay :/

I've not planned to add a dedicated parameter for that, but I will probably migrate `skip` parameter that expect a Widget to `skipChild` and add a new `skipWidget` parameter to have a full custom button solution. But skip event will need to be done manually. I take the example for skip, but same this with next, back and done button.

I close this issue.

**Comment by Macacoazul01** [comment]
@Pyozer when the 3.0 will be avaliable on pub.dev?

**Comment by Pyozer** [comment]
@Macacoazul01 In next days, need to take some time to add the new parameters and do more tests before release
