### ISSUE TITLE
Number of dots

### ISSUE THREAD

**Issue by steveroderickIntrohive** [Pyozer/introduction_screen#7]
Is there a limit to the number of dots - I have more than 6 and they overflow.

**Comment by Pyozer** [comment]
Hi ;)

There is no limit, by default the space of Skip button, dots and next/done button have same space (each have a flex of 1). So if the screen have not enough space, it will have an overflow.

You can change the flex ratio (set 0 on buttons to disable the expanded behaviour), tell dots to take all space they need.
