### ISSUE TITLE
Change order of Title / Image / Body

### ISSUE THREAD

**Issue by filmlovr** [Pyozer/introduction_screen#70]
Hi

Thanks for this very useful library.

Quick question though, is there any way I can have the Title at the top, above the image, with body text underneath the image? Currently have to swap body and image around and use reverse, but this then messes with the footer property.

Thanks

**Comment by Pyozer** [comment]
Hi, so confused for delay :/ 

Probably too late, but you can simply set your title in the `image` param and your image in the `titleWidget`.
After that play with flex using `decoration` param to have desired layout.
