### ISSUE TITLE
Next, Done and Skip buttons have Inkwell, how to turn that of?

### ISSUE THREAD

**Issue by SilkeNL** [Pyozer/introduction_screen#75]

**Comment by Anurag-Pola** [comment]
Is there a way to do this?? @SilkeNL @Pyozer

**Comment by techouse** [comment]
No way to do this other than to hack the source?

**Comment by Pyozer** [comment]
In current version it's not possible to avoid that. Not many time to update this package but you can made an PR.

**Comment by techouse** [comment]
Actually there is :) Just add `splashFactory: NoSplash.splashFactory,` to yorur theme :)

**Comment by techouse** [comment]
I made a PR #101 which addresses this issue.

**Comment by Pyozer** [comment]
@techouse Thank you ;) I will try to check this today
