### ISSUE TITLE
Make title optional 

### ISSUE THREAD

**Issue by gidrokolbaska** [Pyozer/introduction_screen#77]
Hello! First of all - great package. Is it possible to make a title of the PageViewModel optional?

**Comment by Sheikh-X** [comment]
You can make the title of the pageview an empty string as a workaround like this
 title: "",

**Comment by Pyozer** [comment]
Hi ;) Sorry for delay.

Yes you can provide an empty string or empty titleWidget.
If you want, you can made a PR to add this optional title feature.
