### ISSUE TITLE
Multiple pages with Introduction_screen

### ISSUE THREAD

**Issue by LiveRock** [Pyozer/introduction_screen#83]
Hi

I am using introduction_screen as Help Pages in multiple screen in multiple files.
It is ok except that all the instances of introduction_screen share the same Position.
Os, if one instance has 5 dots and I have navigated to the last (fifth) page, and I go to another instance that has lesser pages, I will get the following error:

Another exception was thrown: 
```
package:dots_indicator/src/dots_indicator.dart': Failed assertion: line 34 pos 11
<dotsCount': Position must be inferior than dotsCount
```

How do I resolve this?

**Comment by Pyozer** [comment]
Sorry for the delay, I don't know how is that possible if your IntroductionScreen widget instance is different on all screens.

I'm closing the issue as I assume you have solved it since your post.
