### ISSUE TITLE
Get current position outter Introduction screen

### ISSUE THREAD

**Issue by ThibautSilva** [Pyozer/introduction_screen#87]
Hi, i'm looking for retrieve current position of introductionScreen because I want a custom gradient background in a container above IntroductionScreen Widget.

Can you help me with this ? thanks

**Comment by Pyozer** [comment]
Hi, sorry for delay :/

You can set a key and access to state of IntroductionScreen widget and get current page.
Example:
```dart
final introKey = GlobalKey<IntroductionScreenState>();

void yourFunction() {
    final currentPage = introKey.currentState?.controller.page ?? 0.0;
}

@override
Widget build(BuildContext context) {
    return IntroductionScreen(
        key: introKey, 
        ...
    );
}
```
