### ISSUE TITLE
'(showNextButton && next != null) || !showNextButton': is not true.

### ISSUE THREAD

**Issue by huxaiphaer** [Pyozer/introduction_screen#88]
Am having this issue while running on an Android device :

`'package:introduction_screen/src/introduction_screen.dart': Failed assertion: line 209 pos 16: '(showNextButton && next != null) || !showNextButton': is not true`

But works fine on IOS.

The version am using is :
```
introduction_screen: ^2.0.0
```

also tried :

```
introduction_screen:2.1.0
```

but still the same error.

**Comment by nguyendangkhoi** [comment]
required set showNextButton: false or true

**Comment by huxaiphaer** [comment]
I just commented the line and it worked, but why is this caused @nguyendangkhoi ?

**Comment by Harshsk-create** [comment]
As the error says, you need a text to show your NEXT button. Since you have not provided that, you are getting the error. But when you commented your  showNextButton it worked as you have not provided next button so no text needed for it. 

Solution - 
showNextButton: true,
next: Text('Next'),

**Comment by AlexanderThiele** [comment]
Hey, 
i had the same. Setting the next property solved the issue.

**Comment by Emmanuel2J** [comment]
> you don't need to. just add
> 
> `next: Text("Next")`
> 
> to your element. this should fix the issue.

thanks man
