### ISSUE TITLE
Handle skip and next action outside introduction view

### ISSUE THREAD

**Issue by nguyendangkhoi** [Pyozer/introduction_screen#89]
my case globalFooter button event active next action or skip to last page

**Comment by rox999** [comment]
> my case globalFooter button event active next action or skip to last page

I am having the same issue. Did you get any solution?

**Comment by Pyozer** [comment]
Sorry for delay,

You can use a key to access IntroductionScreenState and call `.next()` or `.skipToEnd()` function.

Example:
```dart
final introKey = GlobalKey<IntroductionScreenState>();

void nextPage() {
    introKey.currentState?.next();
}

void skipPages() {
    introKey.currentState?.skipToEnd();
}

@override
Widget build(BuildContext context) {
    return IntroductionScreen(
      key: introKey,
      ...
   );
}
```
