### ISSUE TITLE
How can i use full screen background image for onboarding? 

### ISSUE THREAD

**Issue by Zeeshan0201** [Pyozer/introduction_screen#9]
How can i use full screen background image for onboarding?

**Comment by fil7er** [comment]
up

**Comment by JeffLima16** [comment]
up :(

**Comment by Pyozer** [comment]
Hi, sorry for the very very late reply :/
I've just merge a PR to set a fullscreen image on a page (update on Pub.dev very soon available)
Also, like this issue #17, you can set the param `globalBackgroundColor` as `Colors.transparent` and wrap the `IntroductionScreen` widget in a `Stack`, and use `Image` widget to set the background. (Stack [ Image, IntroductionScreen ] )
Hope it's can help you ;)
I close this issue, you can re-open it if you have more questions.

**Comment by mudassir060** [comment]
PageViewModel(
          title: "Title of first page",
          bodyWidget:    Container(
            height: MediaQuery.of(context).size.height,
            width: MediaQuery.of(context).size.width,
            decoration: BoxDecoration(
                image: DecorationImage(image: AssetImage(Route_1))),),),
