### ISSUE TITLE
How to centre the image to the centre of the screen ? i need the image to be exactly in the middle of the s 

### ISSUE THREAD

**Issue by Fearripper** [Pyozer/introduction_screen#92]
i need the image to be exactly in the middle of the screen but even if I use imagealign  the image does not centre to the screen

**Comment by UmairJibran** [comment]
Is there a way to center it vertically as well? in my case, I do not have `title` or `body` so if I leave them empty, there is awkwardly huge space between the bottom bar and the images, I would prefer if there was a way to center it vertically as well.

**Comment by Pyozer** [comment]
Hi, yes wrap your image in a `Center` widget to center horizontally and vertically.
For title and body, you can provide `const SizedBox()` to have an empty title and body and set their flex to `0` and image flex to `1` using `decoration` parameter of pages.
