### ISSUE TITLE
How do I use onDone?

### ISSUE THREAD

**Issue by Emmanuel2J** [Pyozer/introduction_screen#93]
I want that when I press the done button, that the screen displays an image and some text underneath it. 
I am a beginner so any help would be very nice.

**Comment by Pyozer** [comment]
Hi, sorry for my late response. I'm not sure to understand what you want.
You want to display an image and text under the introduction widget ? Like a footer below skip/next/done buttons ?

**Comment by ghenry** [comment]
Hi @Emmanuel2J 

I'm going to close this as its been over a year now and we presume you're all OK. This really isn't an issue for this project either, more of a Flutter app design decision for you. Did you try on SO or the Flutter mailing list?

Thanks,
Gavin.
