### ISSUE TITLE
Missing onNext Function

### ISSUE THREAD

**Issue by TolgaYld** [Pyozer/introduction_screen#96]
Hi,

thanks for this package! :)

i missing a function "onNext()". Maybe i want to validate inputs before i switch to the next page. OnChange is useless in this case, because i want to validate before i switch to the next page. And also need activated/deactivated nextbutton (and done button), to say switch to next page or not.

And is there an option to switch with a function to a specific pageviewmodel (page) via giving a index parameter to a function?

thanks in advance! :)

**Comment by Pyozer** [comment]
Hi, you can use `freeze` and `showSkip/Next/Back/DoneButton` parameters.

When user enter on a specific page (listen onChange callback), you can change `freeze` state to `true` and `show...Button` to `false`.
And when user validate inputs, you can unfreeze pages with changing `freeze` state to `false` and other `show...Button` to `true`.

Hope it's can help you.

But your idea to have a `onNext` callback that can return `true` or `false` to go on next page or not, is good. Do not hesitate to made a PR ;)
