### ISSUE TITLE
'firstIndex == 0 || childScrollOffset(firstChild!)! - scrollOffset <= precisionErrorTolerance': is not true

### ISSUE THREAD

**Issue by zeddyyz** [Pyozer/introduction_screen#97]
![Screen Shot 2021-12-20 at 1 13 39 AM](https://user-images.githubusercontent.com/43095019/146720239-dabece38-053e-4a79-9178-f6d6f71413ef.png)

Exception occurs on the last page, either via scrolling or clicking the "Next" button.

I've copied the code from "Example" tab on pub.dev, made a few modifications (removed last 3 PageViewModel() from within "pages: []", changed the text and images. Everything loads fine, including the last page. Once the last page loads and is displayed, then the exception is thrown.

Any help would be appareciated.

**Comment by cybrox** [comment]
Our app throws the same error, though it is much less consistent in our case.    

It happens on screen index `3` (total of 5 screens, `0..4`), so the second to last screen, but only every 10th or so time.

I know this isn't much to go on, just wanted to let you know it not only happens on the last screen.

**Comment by Pyozer** [comment]
Hi, it's weird, have you find a solution ?

**Comment by KDVan** [comment]
Has anyone found a solution, can I ignore it though?

**Comment by ghenry** [comment]
Hi all,

Closing this as it's not had any activity. Please re-open if you would like help.

Thanks,
Gavin.
