### ISSUE TITLE
Adding a global header with skip text button, how to implement skip functionality

### ISSUE THREAD

**Issue by Abdelraman** [Pyozer/introduction_screen#99]
Adding a global header with skip text button, how to implement skip functionality, since there is no option to use the page controller to jump to the latest page

**Comment by Pyozer** [comment]
Hello, you can use a key to access some public function of IntroductionScreenState.

Exemple : 
```dart
final introKey = GlobalKey<IntroductionScreenState>();

void skipPage() {
    introKey.currentState?.skipToEnd();
}

@override
Widget build(BuildContext context) {
    return IntroductionScreen(
        key: introKey,
        ....
    );
}
```


It's not the best but if I got time, I will improve this by creating an IntroductionController.
